### ISSUE TITLE
Day 4 R: KEGG library issue

### ISSUE THREAD

**Issue by kmhandley** [GenomicsAotearoa/metagenomics_summer_school#87] opened 2024-09-02 06:58 UTC
Not sure why I'm just seeing this now when trying to re-run the KEGG workflow, but pathview throws this error:

`library(pathview)`
Error: package or namespace load failed for ‘pathview’ in runHook(".onLoad", env, package.lib, package):
 lazy-load database '/opt/nesi/CS400_centos7_bdw/R-bundle-Bioconductor/3.15-gimkl-2022a-R-4.2.1/Biostrings/R/Biostrings.rdb' is corrupt
In addition: Warning message:
In runHook(".onLoad", env, package.lib, package) :
  internal error -3 in R_decompress1

and then:

##4. Identify pathway maps of interest¶
`keggFind(database = "pathway", query = "TCA cycle")`
Error in keggFind(database = "pathway", query = "TCA cycle") : 
  could not find function "keggFind"

**Comment by DininduSenanayake** [comment] 2024-09-04 23:03
This is due to `pathview` package not getting exported to `.libPaths()`
* `pathview` package is coming from **R-bundle-Bioconductor/3.15-gimkl-2022a-R-4.2.1** module which is the one we have setup for all attendees. Looks like RStudio console is dropping the library path belong to R-bundle-Bioconductor module for some accounts. ( we can reproduce the error with Annie's account as well)
*  Having said that,  all of the attendee accounts we checked didn't trigger any errors. 
* Also, if we are to encounter this, solution is to run the following which will export the correct library path and make it the default for current session

```r
.libPaths(c("/opt/nesi/CS400_centos7_bdw/R-bundle-Bioconductor/3.15-gimkl-2022a-R-4.2.1", .libPaths()))
```

This is a bug in R-bundle-Bioconductor module than RStudio which will be fixed as we migrate to the new platform.

**Closed as completed by DininduSenanayake** 2024-09-04 23:03 UTC
